In [2]:
!pip install keras
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
##How data looks like?
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
##Step : 1 : Know the data
print(type(dataset))
print(len(dataset))

#Dataset is in bunch format. Bunch is a dictionary like object.
print(dataset.keys())

#We try to find out what values are stored in these attributes
print(dataset[ 'data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])

#Next we define our x and y y is the dependent on x
x=dataset['data']
print(len(x)) #To check length of dataset
y=dataset[ 'target']
print(len(y)) #To check length of targets
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [4]:
#46tep : 2 : Convert y into one hot encoded vector
#One hot encoding is used because V has labels (0,1,2)- which is a categorical categorical data with no ordinal relationships
from keras.utils import to_categorical
Ny=len(np.unique(y))
print(Ny)
Y=to_categorical(y,num_classes=Ny)
print(Y[0:5])

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [5]:
##Step : 3 : Now we split the data into two parts - one +or training another for testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])

[[5.7 2.6 3.5 1. ]
 [6.7 3.3 5.7 2.1]
 [6.  2.2 4.  1. ]
 [6.4 2.8 5.6 2.2]
 [4.8 3.1 1.6 0.2]]
[[6.4 3.2 5.3 2.3]
 [6.7 3.1 5.6 2.4]
 [7.3 2.9 6.3 1.8]
 [5.  3.5 1.3 0.3]
 [5.6 3.  4.5 1.5]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [6]:
##Step : 4 : Then we normalize the data
from sklearn.preprocessing import StandardScaler

#Mormalization is done so that the difference between highest and lowest data point is not too large
import numpy as np
scaler=StandardScaler()

##To find mean and std dcv
scaler.fit(x_train)

##Converting data into form where mean of data is 0 and std dcv is 1
X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))

[2.57756194 3.00524169 1.82639326 1.75150841]
[-1.87567341 -2.40118978 -1.52550128 -1.3977076 ]


In [7]:
##Step : 5 : Now finally we build the model using keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu'))

##D-opout is used to avoid overfitting
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)

##For classification problems, we usually use softmax as activation function in final layer
model.add(Dense(3, activation='softmax'))

##Compiling the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

     ---------------------------------------- 1.5/1.5 MB 2.5 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 2.2 MB/s eta 0:00:00
     -------------------------------------- 895.7/895.7 kB 2.2 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3


In [8]:
##Step : 6 : Know the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 20)                420       
                                                                 
 dense_2 (Dense)             (None, 20)                420       
                                                                 
 dense_3 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [9]:
##Step : 7 ;Train the model
##Batch size,epochs and validation split are all hyper parameters
model.fit(X_train, y_train, epochs=195, batch_size=80, validation_split=0.1)

Epoch 1/195
2/2 [==============================] - 2s 407ms/step - loss: 1.0103 - accuracy: 0.3967 - val_loss: 1.1122 - val_accuracy: 0.2143
Epoch 2/195
2/2 [==============================] - 0s 38ms/step - loss: 0.9860 - accuracy: 0.4050 - val_loss: 1.0920 - val_accuracy: 0.2143
Epoch 3/195
2/2 [==============================] - 0s 44ms/step - loss: 0.9626 - accuracy: 0.4298 - val_loss: 1.0724 - val_accuracy: 0.2857
Epoch 4/195
2/2 [==============================] - 0s 44ms/step - loss: 0.9390 - accuracy: 0.4628 - val_loss: 1.0529 - val_accuracy: 0.2857
Epoch 5/195
2/2 [==============================] - 0s 47ms/step - loss: 0.9156 - accuracy: 0.4876 - val_loss: 1.0341 - val_accuracy: 0.2857
Epoch 6/195
2/2 [==============================] - 0s 46ms/step - loss: 0.8932 - accuracy: 0.5537 - val_loss: 1.0156 - val_accuracy: 0.3571
Epoch 7/195
2/2 [==============================] - 0s 42ms/step - loss: 0.8705 - accuracy: 0.5950 - val_loss: 0.9981 - val_accuracy: 0.3571
Epoch 8/195
2/2 [==

2/2 [==============================] - 0s 44ms/step - loss: 0.2252 - accuracy: 0.9339 - val_loss: 0.2709 - val_accuracy: 1.0000
Epoch 60/195
2/2 [==============================] - 0s 44ms/step - loss: 0.2203 - accuracy: 0.9504 - val_loss: 0.2636 - val_accuracy: 1.0000
Epoch 61/195
2/2 [==============================] - 0s 47ms/step - loss: 0.2150 - accuracy: 0.9587 - val_loss: 0.2567 - val_accuracy: 1.0000
Epoch 62/195
2/2 [==============================] - 0s 39ms/step - loss: 0.2103 - accuracy: 0.9587 - val_loss: 0.2500 - val_accuracy: 1.0000
Epoch 63/195
2/2 [==============================] - 0s 44ms/step - loss: 0.2056 - accuracy: 0.9587 - val_loss: 0.2429 - val_accuracy: 1.0000
Epoch 64/195
2/2 [==============================] - 0s 44ms/step - loss: 0.2012 - accuracy: 0.9587 - val_loss: 0.2358 - val_accuracy: 1.0000
Epoch 65/195
2/2 [==============================] - 0s 45ms/step - loss: 0.1961 - accuracy: 0.9587 - val_loss: 0.2288 - val_accuracy: 1.0000
Epoch 66/195
2/2 [========

2/2 [==============================] - 0s 40ms/step - loss: 0.0738 - accuracy: 0.9669 - val_loss: 0.0594 - val_accuracy: 1.0000
Epoch 118/195
2/2 [==============================] - 0s 44ms/step - loss: 0.0730 - accuracy: 0.9669 - val_loss: 0.0594 - val_accuracy: 1.0000
Epoch 119/195
2/2 [==============================] - 0s 43ms/step - loss: 0.0720 - accuracy: 0.9669 - val_loss: 0.0589 - val_accuracy: 1.0000
Epoch 120/195
2/2 [==============================] - 0s 40ms/step - loss: 0.0713 - accuracy: 0.9669 - val_loss: 0.0572 - val_accuracy: 1.0000
Epoch 121/195
2/2 [==============================] - 0s 42ms/step - loss: 0.0702 - accuracy: 0.9669 - val_loss: 0.0576 - val_accuracy: 1.0000
Epoch 122/195
2/2 [==============================] - 0s 41ms/step - loss: 0.0693 - accuracy: 0.9669 - val_loss: 0.0599 - val_accuracy: 1.0000
Epoch 123/195
2/2 [==============================] - 0s 46ms/step - loss: 0.0688 - accuracy: 0.9752 - val_loss: 0.0611 - val_accuracy: 1.0000
Epoch 124/195
2/2 [=

Epoch 175/195
2/2 [==============================] - 0s 57ms/step - loss: 0.0484 - accuracy: 0.9835 - val_loss: 0.0287 - val_accuracy: 1.0000
Epoch 176/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0479 - accuracy: 0.9835 - val_loss: 0.0299 - val_accuracy: 1.0000
Epoch 177/195
2/2 [==============================] - 0s 62ms/step - loss: 0.0481 - accuracy: 0.9752 - val_loss: 0.0324 - val_accuracy: 1.0000
Epoch 178/195
2/2 [==============================] - 0s 50ms/step - loss: 0.0480 - accuracy: 0.9752 - val_loss: 0.0329 - val_accuracy: 1.0000
Epoch 179/195
2/2 [==============================] - 0s 48ms/step - loss: 0.0476 - accuracy: 0.9752 - val_loss: 0.0312 - val_accuracy: 1.0000
Epoch 180/195
2/2 [==============================] - 0s 61ms/step - loss: 0.0472 - accuracy: 0.9752 - val_loss: 0.0293 - val_accuracy: 1.0000
Epoch 181/195
2/2 [==============================] - 0s 80ms/step - loss: 0.0468 - accuracy: 0.9752 - val_loss: 0.0266 - val_accuracy: 1.0000
Epoch 

In [10]:
##Step : 8 : Get the accuracy of model on testing data
testing=model.evaluate(X_test, y_test)
print ("\n%s: %.2f%%" %(model.metrics_names[1]+'uracy of Model on testing data', testing[1]*100))

1/1 [==============================] - 0s 61ms/step - loss: 0.1706 - accuracy: 0.8667

accuracyuracy of Model on testing data: 86.67%


In [11]:
##Step : 9 : Evaluate our model
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis=1)
Y_test = np.argmax(y_test,axis=1)

#To get confusion matrix
print(confusion_matrix(Y_test,predictions))

#To get values of all evaluation metrics
print(classification_report(Y_test,predictions))

1/1 [==============================] - 0s 217ms/step
[[3 0 0]
 [0 4 0]
 [0 2 6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       0.67      1.00      0.80         4
           2       1.00      0.75      0.86         8

    accuracy                           0.87        15
   macro avg       0.89      0.92      0.89        15
weighted avg       0.91      0.87      0.87        15

